name: 'Upload to Bunny.net Storage Zone'
description: "Uploads files to the Edge Storage Zone on Bunny.net and allows purging of Pull Zones linked to the account."
author: 'Rafael Meneses'

branding:
  icon: 'upload-cloud'
  color: 'orange'

inputs:
  storage_zone:
    description: 'Storage zone name or ID'
    required: true
  api_key:
    description: 'Bunny account API key'
    required: true
  local_path:
    description: 'The local path of the directory or file to be uploaded'
    required: true
  remote_path:
    description: 'The path of the remote subdirectory in the Storage Zone where the files will be uploaded'
    required: false
    default: ''
  remove_old_files:
    description: 'If "true", remove all files from remote-path before uploading new ones.'
    required: false
    default: 'false'
  purge_after_upload:
    description: 'If "true", purge the CDN cache after uploading files.'
    required: false
    default: 'false'

outputs:
  files_uploaded:
    description: 'Files uploaded successfully.'
  files_deleted:
    description: 'Files deleted successfully.'
  files_failed_upload:
    description: 'Files that failed to upload.'
  files_failed_delete:
    description: 'Files that failed to delete.'
  uploaded_files_json:
    description: 'A JSON string with the list of uploaded files.'

runs:
  using: 'docker'
  image: 'Dockerfile'
